[package]
name = "goffi_gen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fcplug = "*"
protobuf = "3.2.0"
flatbuffers = "23.5.26"
