// Code generated by fcplug. DO NOT EDIT.

package echo

/*
   #cgo CFLAGS: -I/Users/henrylee2cn/rust/fcplug/target/debug
   #cgo LDFLAGS: -L/Users/henrylee2cn/rust/fcplug/target/debug -lecho -ldl -lm

   #include "echo.h"
*/
import "C"

import (
	"errors"
	"fmt"
	"reflect"
	"unsafe"
)

var (
	_ = errors.New
	_ = fmt.Sprintf
	_ reflect.SliceHeader
	_ unsafe.Pointer
)

type A struct {
	Number int32 `json:"number"`
}

type Pong struct {
	Msg       string      `json:"msg"`
	NumberMap map[int16]A `json:"number_map"`
}

type Ping struct {
	Msg        string `json:"msg"`
	NumberList []A    `json:"number_list"`
	NumberSet  []A    `json:"number_set"`
}

var GlobalRustFfi RustFfi = RustFfiImpl{}

type RustFfi interface {
}
type RustFfiImpl struct{}
