// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rsffi_gen

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type EchoResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsEchoResponse(buf []byte, offset flatbuffers.UOffsetT) *EchoResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &EchoResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishEchoResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsEchoResponse(buf []byte, offset flatbuffers.UOffsetT) *EchoResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &EchoResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedEchoResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *EchoResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *EchoResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *EchoResponse) Data() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func EchoResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func EchoResponseAddData(builder *flatbuffers.Builder, data flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(data), 0)
}
func EchoResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
