// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package rsffi_gen

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type EchoRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsEchoRequest(buf []byte, offset flatbuffers.UOffsetT) *EchoRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &EchoRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishEchoRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsEchoRequest(buf []byte, offset flatbuffers.UOffsetT) *EchoRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &EchoRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedEchoRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *EchoRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *EchoRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *EchoRequest) Data() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func EchoRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func EchoRequestAddData(builder *flatbuffers.Builder, data flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(data), 0)
}
func EchoRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
