// Code generated by fcplug. DO NOT EDIT.

package main

/*
   #cgo CFLAGS: -I/Users/henrylee2cn/rust/fcplug/target/debug
   #cgo LDFLAGS: -L/Users/henrylee2cn/rust/fcplug/target/debug -lecho -ldl -lm

   #include "echo.h"
*/
import "C"
import (
	"reflect"
	"unsafe"
)

// main function is never called by C to.
func main() {}

var (
	_ reflect.SliceHeader
	_ unsafe.Pointer
)

var GlobalGoFfi GoFfi = _UnimplementedGoFfi{}

type GoFfi interface {
}
type _UnimplementedGoFfi struct{}
