// Code generated by protoc-gen-go. DO NOT EDIT.
// source: demo.proto

package demo

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// import "google/protobuf/empty.proto";
type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca53982754088a9d, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type SearchRequest struct {
	Query                string   `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	PageNumber           int32    `protobuf:"varint,2,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
	ResultPerPage        int32    `protobuf:"varint,3,opt,name=result_per_page,json=resultPerPage,proto3" json:"result_per_page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchRequest) Reset()         { *m = SearchRequest{} }
func (m *SearchRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()    {}
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca53982754088a9d, []int{1}
}

func (m *SearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRequest.Unmarshal(m, b)
}
func (m *SearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRequest.Marshal(b, m, deterministic)
}
func (m *SearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRequest.Merge(m, src)
}
func (m *SearchRequest) XXX_Size() int {
	return xxx_messageInfo_SearchRequest.Size(m)
}
func (m *SearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRequest proto.InternalMessageInfo

func (m *SearchRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *SearchRequest) GetPageNumber() int32 {
	if m != nil {
		return m.PageNumber
	}
	return 0
}

func (m *SearchRequest) GetResultPerPage() int32 {
	if m != nil {
		return m.ResultPerPage
	}
	return 0
}

type Server struct {
	Hostname             string   `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Port                 int32    `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Server) Reset()         { *m = Server{} }
func (m *Server) String() string { return proto.CompactTextString(m) }
func (*Server) ProtoMessage()    {}
func (*Server) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca53982754088a9d, []int{2}
}

func (m *Server) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Server.Unmarshal(m, b)
}
func (m *Server) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Server.Marshal(b, m, deterministic)
}
func (m *Server) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Server.Merge(m, src)
}
func (m *Server) XXX_Size() int {
	return xxx_messageInfo_Server.Size(m)
}
func (m *Server) XXX_DiscardUnknown() {
	xxx_messageInfo_Server.DiscardUnknown(m)
}

var xxx_messageInfo_Server proto.InternalMessageInfo

func (m *Server) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *Server) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type WebSite struct {
	Name                 string             `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Link                 string             `protobuf:"bytes,2,opt,name=link,proto3" json:"link,omitempty"`
	Age                  int32              `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	Server               map[string]*Server `protobuf:"bytes,4,rep,name=server,proto3" json:"server,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	A                    []string           `protobuf:"bytes,5,rep,name=a,proto3" json:"a,omitempty"`
	B                    []byte             `protobuf:"bytes,6,opt,name=b,proto3" json:"b,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *WebSite) Reset()         { *m = WebSite{} }
func (m *WebSite) String() string { return proto.CompactTextString(m) }
func (*WebSite) ProtoMessage()    {}
func (*WebSite) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca53982754088a9d, []int{3}
}

func (m *WebSite) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WebSite.Unmarshal(m, b)
}
func (m *WebSite) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WebSite.Marshal(b, m, deterministic)
}
func (m *WebSite) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WebSite.Merge(m, src)
}
func (m *WebSite) XXX_Size() int {
	return xxx_messageInfo_WebSite.Size(m)
}
func (m *WebSite) XXX_DiscardUnknown() {
	xxx_messageInfo_WebSite.DiscardUnknown(m)
}

var xxx_messageInfo_WebSite proto.InternalMessageInfo

func (m *WebSite) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *WebSite) GetLink() string {
	if m != nil {
		return m.Link
	}
	return ""
}

func (m *WebSite) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *WebSite) GetServer() map[string]*Server {
	if m != nil {
		return m.Server
	}
	return nil
}

func (m *WebSite) GetA() []string {
	if m != nil {
		return m.A
	}
	return nil
}

func (m *WebSite) GetB() []byte {
	if m != nil {
		return m.B
	}
	return nil
}

type Client struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	City                 string   `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Client) Reset()         { *m = Client{} }
func (m *Client) String() string { return proto.CompactTextString(m) }
func (*Client) ProtoMessage()    {}
func (*Client) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca53982754088a9d, []int{4}
}

func (m *Client) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Client.Unmarshal(m, b)
}
func (m *Client) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Client.Marshal(b, m, deterministic)
}
func (m *Client) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Client.Merge(m, src)
}
func (m *Client) XXX_Size() int {
	return xxx_messageInfo_Client.Size(m)
}
func (m *Client) XXX_DiscardUnknown() {
	xxx_messageInfo_Client.DiscardUnknown(m)
}

var xxx_messageInfo_Client proto.InternalMessageInfo

func (m *Client) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *Client) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func init() {
	proto.RegisterType((*Empty)(nil), "Empty")
	proto.RegisterType((*SearchRequest)(nil), "SearchRequest")
	proto.RegisterType((*Server)(nil), "server")
	proto.RegisterType((*WebSite)(nil), "web_site")
	proto.RegisterMapType((map[string]*Server)(nil), "web_site.ServerEntry")
	proto.RegisterType((*Client)(nil), "Client")
}

func init() { proto.RegisterFile("demo.proto", fileDescriptor_ca53982754088a9d) }

var fileDescriptor_ca53982754088a9d = []byte{
	// 397 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0x4d, 0x6f, 0xd4, 0x30,
	0x10, 0x5d, 0x27, 0x9b, 0xa4, 0x99, 0x74, 0x17, 0x64, 0x81, 0x14, 0x45, 0x02, 0x82, 0x0f, 0x28,
	0x42, 0x34, 0x87, 0x70, 0xa9, 0x38, 0x82, 0x5a, 0xc4, 0x05, 0x55, 0xde, 0x03, 0x07, 0x0e, 0x51,
	0xb2, 0x8c, 0xda, 0xa8, 0xf9, 0xaa, 0xed, 0x14, 0xe5, 0x77, 0xf2, 0x87, 0x90, 0x9d, 0xb8, 0x14,
	0x0e, 0x9c, 0xf2, 0xfc, 0xe2, 0xf7, 0xe6, 0x8d, 0x67, 0x00, 0x7e, 0x60, 0x37, 0xe4, 0xa3, 0x18,
	0xd4, 0xc0, 0x02, 0xf0, 0x2e, 0xba, 0x51, 0xcd, 0xac, 0x87, 0xdd, 0x01, 0x2b, 0x71, 0xbc, 0xe1,
	0x78, 0x37, 0xa1, 0x54, 0xf4, 0x19, 0x78, 0x77, 0x13, 0x8a, 0x39, 0x26, 0x29, 0xc9, 0x42, 0xbe,
	0x1c, 0xe8, 0x2b, 0x88, 0xc6, 0xea, 0x1a, 0xcb, 0x7e, 0xea, 0x6a, 0x14, 0xb1, 0x93, 0x92, 0xcc,
	0xe3, 0xa0, 0xa9, 0xaf, 0x86, 0xa1, 0x6f, 0xe0, 0x89, 0x40, 0x39, 0xb5, 0xaa, 0x1c, 0x51, 0x94,
	0xfa, 0x47, 0xec, 0x9a, 0x4b, 0xbb, 0x85, 0xbe, 0x42, 0x71, 0x55, 0x5d, 0x23, 0x3b, 0x07, 0x5f,
	0xa2, 0xb8, 0x47, 0x41, 0x13, 0x38, 0xb9, 0x19, 0xa4, 0xea, 0xab, 0x0e, 0xd7, 0x5a, 0x0f, 0x67,
	0x4a, 0x61, 0x3b, 0x0e, 0x42, 0xad, 0x75, 0x0c, 0x66, 0xbf, 0x08, 0x9c, 0xfc, 0xc4, 0xba, 0x94,
	0x8d, 0x32, 0x17, 0x1e, 0x09, 0xb7, 0x56, 0xd4, 0x36, 0xfd, 0xad, 0x11, 0x85, 0xdc, 0x60, 0xfa,
	0x14, 0xdc, 0x3f, 0x51, 0x34, 0xa4, 0x67, 0x36, 0x40, 0xbc, 0x4d, 0xdd, 0x2c, 0x2a, 0x9e, 0xe7,
	0xd6, 0x34, 0x3f, 0x18, 0xfe, 0xa2, 0x57, 0x62, 0xe6, 0x36, 0xe5, 0x29, 0x90, 0x2a, 0xf6, 0x52,
	0x37, 0x0b, 0x39, 0xa9, 0xf4, 0xa9, 0x8e, 0xfd, 0x94, 0x64, 0xa7, 0x9c, 0xd4, 0xc9, 0x47, 0x88,
	0x1e, 0x49, 0x74, 0xad, 0x5b, 0xb4, 0xef, 0xa6, 0x21, 0x7d, 0x01, 0xde, 0x7d, 0xd5, 0x4e, 0x68,
	0x22, 0x45, 0x45, 0x90, 0x2f, 0xa6, 0x7c, 0x61, 0x3f, 0x38, 0xe7, 0x84, 0xbd, 0x03, 0xff, 0x53,
	0xdb, 0x60, 0xaf, 0xe8, 0x1e, 0x9c, 0x66, 0x5c, 0xd5, 0x4e, 0x33, 0xea, 0x76, 0x8e, 0x8d, 0x9a,
	0x6d, 0x3b, 0x1a, 0x17, 0xdf, 0x21, 0xe0, 0x93, 0x54, 0x97, 0x97, 0x5f, 0xe8, 0x19, 0xec, 0x97,
	0xc1, 0x7d, 0xb3, 0x6f, 0xb2, 0xcf, 0xff, 0x9a, 0x64, 0x12, 0x3e, 0x74, 0xc6, 0x36, 0xf4, 0x35,
	0xec, 0x84, 0x2c, 0x15, 0x4a, 0x55, 0xa2, 0x1e, 0x3c, 0xf5, 0x73, 0xb3, 0x00, 0xc9, 0xfa, 0x65,
	0x9b, 0xe2, 0x00, 0xde, 0xe7, 0x41, 0x5b, 0xbf, 0xb5, 0x3b, 0x51, 0x1e, 0xd7, 0x68, 0xff, 0x38,
	0x07, 0xf9, 0x92, 0x99, 0x6d, 0xe8, 0x4b, 0x80, 0xff, 0x99, 0xd6, 0xbe, 0xd9, 0xb7, 0xf7, 0xbf,
	0x03, 0x00, 0x00, 0xff, 0xff, 0x03, 0x27, 0xe0, 0x1b, 0x7d, 0x02, 0x00, 0x00,
}
