// Code generated by fcplug. DO NOT EDIT.
#![allow(warnings, clippy::all)]
#[derive(PartialOrd, Hash, Eq, Ord, Debug, Default, ::serde::Serialize, ::serde::Deserialize)]
#[repr(C)]
#[derive(Clone, PartialEq)]
pub struct A {
    pub number: i32,
}
#[derive(Debug, Default, ::serde::Serialize, ::serde::Deserialize, Clone, PartialEq)]
pub struct Pong {
    pub msg: ::std::string::String,

    pub number_map: ::std::collections::HashMap<i16, A>,
}
pub(super) trait GoFfi {}

pub trait GoFfiCall {}
#[derive(
    PartialOrd,
    Hash,
    Eq,
    Ord,
    Debug,
    Default,
    ::serde::Serialize,
    ::serde::Deserialize,
    Clone,
    PartialEq,
)]
pub struct Ping {
    pub msg: ::std::string::String,

    pub number_list: ::std::vec::Vec<A>,

    pub number_set: ::std::vec::Vec<A>,
}
pub(super) trait RustFfi {}
trait Ffi: RustFfi + GoFfi + GoFfiCall {}

pub struct FfiImpl;

impl GoFfiCall for FfiImpl {}
impl Ffi for FfiImpl {}
